### ISSUE TITLE
Charm command broken

### ISSUE THREAD

**Issue by urosj** [juju/charmstore-client#7]
parallels@ubuntu:~/go/src/github.com/juju/charmstore-client$ charm
2016-03-22 00:10:42 ERROR charm.cmd.charm plugin.go:151 'charm-getall --description': exit status 2
2016-03-22 00:10:42 ERROR charm.cmd.charm plugin.go:151 'charm-create --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-info --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-list --description': exit status 1
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-get --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-inspect --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-generate --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-build --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-compose --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-add --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-layers --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-review --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-promulgate --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-review-queue --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-refresh --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-proof --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-subscribers --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-search --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-unpromulgate --description': exit status 2
2016-03-22 00:10:43 ERROR charm.cmd.charm plugin.go:151 'charm-update --description': exit status 2
panic: command already registered: "list"

goroutine 1 [running]:
runtime.panic(0x7b5f80, 0xc210259410)
    /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/juju/cmd.(_SuperCommand).insert(0xc210051500, 0xc210147b2f, 0x4, 0x7f2647fb36d8, 0xc2100fdf50, ...)
    /home/parallels/go/src/github.com/juju/cmd/supercommand.go:255 +0x164
github.com/juju/cmd.(_SuperCommand).Register(0xc210051500, 0x7f2647fb36d8, 0xc2100fdf50)
    /home/parallels/go/src/github.com/juju/cmd/supercommand.go:177 +0xc3
github.com/juju/charmstore-client/cmd/charm/charmcmd.registerPlugins(0xc210051500)
    /home/parallels/go/src/github.com/juju/charmstore-client/cmd/charm/charmcmd/cmd.go:123 +0x1ef
github.com/juju/charmstore-client/cmd/charm/charmcmd.New(0x8bc060, 0xc210020230)
    /home/parallels/go/src/github.com/juju/charmstore-client/cmd/charm/charmcmd/cmd.go:108 +0x62a
main.main()
    /home/parallels/go/src/github.com/juju/charmstore-client/cmd/charm/main.go:23 +0xf1

goroutine 4 [syscall]:
os/signal.loop()
    /usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
    /usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 81 [finalizer wait]:
runtime.park(0x40b620, 0xede0b0, 0xeda4a8)
    /usr/lib/go/src/pkg/runtime/proc.c:1342 +0x66
runfinq()
    /usr/lib/go/src/pkg/runtime/mgc0.c:2279 +0x84
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1394

**Comment by urosj** [comment]
Fixed.
